export enum DISCOUNT_TYPES {
  PERCENTAGE = "percentage",
  FIXED_AMOUNT = "fixed_amount",
} 

export enum COUPON_PRODUCT_RESTRICTIONS {
  ALL_PRODUCTS = 'ALL_PRODUCTS',
  SPECIFIC_PRODUCTS = 'SPECIFIC_PRODUCTS',
  SPECIFIC_CATEGORIES = 'SPECIFIC_CATEGORIES'
}